<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SharpCompress">
      <HintPath>SharpCompress.0.29.0/lib/net5.0/SharpCompress.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
